name: Go

on:
  pull_request:
    branches: [ master, prod ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        env:
          GO111MODULE: on
          GOPRIVATE: github.com/KompiTech/*
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Set Up for tests
        run: |
          mkdir -p ~/.ssh/
          echo "$GITHUB_PRIVATE_KEY" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
          git config --global url."git@github.com:KompiTech/".insteadOf "https://github.com/KompiTech/"
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        env:
          GO111MODULE: on
          GOPRIVATE: github.com/KompiTech/*
          GITHUB_PRIVATE_KEY: ${{secrets.DO_GITHUB_PRIVATE_KEY}}
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      - name: Test
        run: make test-all
        env:
          GO111MODULE: on
          GOPRIVATE: github.com/KompiTech/*